name: DevSecOps CI/CD Guardrails

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
secrets-scan:
    name: 1. Secrets Detection (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  iac-scan:
    name: 2. IaC Security Scan (Checkov)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Checkov IaC Scanner
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true

  container-scan:
    name: 3. Container Vulnerability Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build local image
        run: docker build -t local-test-image:latest .
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-test-image:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
